/*
 * generated by Xtext 2.12.0
 */
package io.github.jhipster.xjdl.validation


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class XjdlValidator extends AbstractXjdlValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					XjdlPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
