/*
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.dsl.idea.lang;

import com.intellij.openapi.fileTypes.FileTypeConsumer;
import com.intellij.openapi.fileTypes.FileTypeFactory;
import org.jetbrains.annotations.NotNull;

public class JDLFileTypeFactory extends FileTypeFactory {

	@Override
	public void createFileTypes(@NotNull FileTypeConsumer consumer) {
		consumer.consume(JDLFileType.INSTANCE, AbstractJDLFileType.DEFAULT_EXTENSION);
	}

}
