/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.dsl.jdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Double Field</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.github.jhipster.jdl.dsl.jdl.JdlPackage#getDoubleField()
 * @model
 * @generated
 */
public interface DoubleField extends NumericField
{
} // DoubleField
