/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.dsl.jdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.github.jhipster.jdl.dsl.jdl.JdlPackage#getField()
 * @model
 * @generated
 */
public interface Field extends EObject
{
} // Field
