/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.dsl.jdl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Generation Setting</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.jhipster.jdl.dsl.jdl.GenerationSetting#getEntities <em>Entities</em>}</li>
 * </ul>
 *
 * @see io.github.jhipster.jdl.dsl.jdl.JdlPackage#getGenerationSetting()
 * @model
 * @generated
 */
public interface GenerationSetting extends Elements
{
  /**
   * Returns the value of the '<em><b>Entities</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entities</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' attribute list.
   * @see io.github.jhipster.jdl.dsl.jdl.JdlPackage#getGenerationSetting_Entities()
   * @model unique="false"
   * @generated
   */
  EList<String> getEntities();

} // GenerationSetting
