/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.dsl.jdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Paginate Generation Setting</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.jhipster.jdl.dsl.jdl.PaginateGenerationSetting#getPaginateType <em>Paginate Type</em>}</li>
 * </ul>
 *
 * @see io.github.jhipster.jdl.dsl.jdl.JdlPackage#getPaginateGenerationSetting()
 * @model
 * @generated
 */
public interface PaginateGenerationSetting extends GenerationSetting
{
  /**
   * Returns the value of the '<em><b>Paginate Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Paginate Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paginate Type</em>' containment reference.
   * @see #setPaginateType(PaginateType)
   * @see io.github.jhipster.jdl.dsl.jdl.JdlPackage#getPaginateGenerationSetting_PaginateType()
   * @model containment="true"
   * @generated
   */
  PaginateType getPaginateType();

  /**
   * Sets the value of the '{@link io.github.jhipster.jdl.dsl.jdl.PaginateGenerationSetting#getPaginateType <em>Paginate Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Paginate Type</em>' containment reference.
   * @see #getPaginateType()
   * @generated
   */
  void setPaginateType(PaginateType value);

} // PaginateGenerationSetting
