/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.dsl.jdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relationship</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.jhipster.jdl.dsl.jdl.Relationship#getFromEntity <em>From Entity</em>}</li>
 *   <li>{@link io.github.jhipster.jdl.dsl.jdl.Relationship#getFromName <em>From Name</em>}</li>
 *   <li>{@link io.github.jhipster.jdl.dsl.jdl.Relationship#getToEntity <em>To Entity</em>}</li>
 *   <li>{@link io.github.jhipster.jdl.dsl.jdl.Relationship#getToName <em>To Name</em>}</li>
 * </ul>
 *
 * @see io.github.jhipster.jdl.dsl.jdl.JdlPackage#getRelationship()
 * @model
 * @generated
 */
public interface Relationship extends EObject
{
  /**
   * Returns the value of the '<em><b>From Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>From Entity</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Entity</em>' containment reference.
   * @see #setFromEntity(Entity)
   * @see io.github.jhipster.jdl.dsl.jdl.JdlPackage#getRelationship_FromEntity()
   * @model containment="true"
   * @generated
   */
  Entity getFromEntity();

  /**
   * Sets the value of the '{@link io.github.jhipster.jdl.dsl.jdl.Relationship#getFromEntity <em>From Entity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From Entity</em>' containment reference.
   * @see #getFromEntity()
   * @generated
   */
  void setFromEntity(Entity value);

  /**
   * Returns the value of the '<em><b>From Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>From Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Name</em>' containment reference.
   * @see #setFromName(RelationshipName)
   * @see io.github.jhipster.jdl.dsl.jdl.JdlPackage#getRelationship_FromName()
   * @model containment="true"
   * @generated
   */
  RelationshipName getFromName();

  /**
   * Sets the value of the '{@link io.github.jhipster.jdl.dsl.jdl.Relationship#getFromName <em>From Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From Name</em>' containment reference.
   * @see #getFromName()
   * @generated
   */
  void setFromName(RelationshipName value);

  /**
   * Returns the value of the '<em><b>To Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To Entity</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>To Entity</em>' containment reference.
   * @see #setToEntity(Entity)
   * @see io.github.jhipster.jdl.dsl.jdl.JdlPackage#getRelationship_ToEntity()
   * @model containment="true"
   * @generated
   */
  Entity getToEntity();

  /**
   * Sets the value of the '{@link io.github.jhipster.jdl.dsl.jdl.Relationship#getToEntity <em>To Entity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To Entity</em>' containment reference.
   * @see #getToEntity()
   * @generated
   */
  void setToEntity(Entity value);

  /**
   * Returns the value of the '<em><b>To Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>To Name</em>' containment reference.
   * @see #setToName(RelationshipName)
   * @see io.github.jhipster.jdl.dsl.jdl.JdlPackage#getRelationship_ToName()
   * @model containment="true"
   * @generated
   */
  RelationshipName getToName();

  /**
   * Sets the value of the '{@link io.github.jhipster.jdl.dsl.jdl.Relationship#getToName <em>To Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To Name</em>' containment reference.
   * @see #getToName()
   * @generated
   */
  void setToName(RelationshipName value);

} // Relationship
