/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.dsl.jdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Service Generation Setting</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.jhipster.jdl.dsl.jdl.ServiceGenerationSetting#getServiceType <em>Service Type</em>}</li>
 * </ul>
 *
 * @see io.github.jhipster.jdl.dsl.jdl.JdlPackage#getServiceGenerationSetting()
 * @model
 * @generated
 */
public interface ServiceGenerationSetting extends GenerationSetting
{
  /**
   * Returns the value of the '<em><b>Service Type</b></em>' attribute.
   * The literals are from the enumeration {@link io.github.jhipster.jdl.dsl.jdl.ServiceType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Service Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Service Type</em>' attribute.
   * @see io.github.jhipster.jdl.dsl.jdl.ServiceType
   * @see #setServiceType(ServiceType)
   * @see io.github.jhipster.jdl.dsl.jdl.JdlPackage#getServiceGenerationSetting_ServiceType()
   * @model
   * @generated
   */
  ServiceType getServiceType();

  /**
   * Sets the value of the '{@link io.github.jhipster.jdl.dsl.jdl.ServiceGenerationSetting#getServiceType <em>Service Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Service Type</em>' attribute.
   * @see io.github.jhipster.jdl.dsl.jdl.ServiceType
   * @see #getServiceType()
   * @generated
   */
  void setServiceType(ServiceType value);

} // ServiceGenerationSetting
