/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.dsl.jdl.impl;

import io.github.jhipster.jdl.dsl.jdl.JdlPackage;
import io.github.jhipster.jdl.dsl.jdl.NumericField;
import io.github.jhipster.jdl.dsl.jdl.NumericValidators;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Numeric Field</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.github.jhipster.jdl.dsl.jdl.impl.NumericFieldImpl#getValidators <em>Validators</em>}</li>
 * </ul>
 *
 * @generated
 */
public class NumericFieldImpl extends FieldImpl implements NumericField
{
  /**
   * The cached value of the '{@link #getValidators() <em>Validators</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValidators()
   * @generated
   * @ordered
   */
  protected NumericValidators validators;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NumericFieldImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JdlPackage.Literals.NUMERIC_FIELD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NumericValidators getValidators()
  {
    return validators;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetValidators(NumericValidators newValidators, NotificationChain msgs)
  {
    NumericValidators oldValidators = validators;
    validators = newValidators;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JdlPackage.NUMERIC_FIELD__VALIDATORS, oldValidators, newValidators);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValidators(NumericValidators newValidators)
  {
    if (newValidators != validators)
    {
      NotificationChain msgs = null;
      if (validators != null)
        msgs = ((InternalEObject)validators).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JdlPackage.NUMERIC_FIELD__VALIDATORS, null, msgs);
      if (newValidators != null)
        msgs = ((InternalEObject)newValidators).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JdlPackage.NUMERIC_FIELD__VALIDATORS, null, msgs);
      msgs = basicSetValidators(newValidators, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JdlPackage.NUMERIC_FIELD__VALIDATORS, newValidators, newValidators));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JdlPackage.NUMERIC_FIELD__VALIDATORS:
        return basicSetValidators(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JdlPackage.NUMERIC_FIELD__VALIDATORS:
        return getValidators();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JdlPackage.NUMERIC_FIELD__VALIDATORS:
        setValidators((NumericValidators)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JdlPackage.NUMERIC_FIELD__VALIDATORS:
        setValidators((NumericValidators)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JdlPackage.NUMERIC_FIELD__VALIDATORS:
        return validators != null;
    }
    return super.eIsSet(featureID);
  }

} //NumericFieldImpl
