/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.dsl.jdl.impl;

import io.github.jhipster.jdl.dsl.jdl.Entity;
import io.github.jhipster.jdl.dsl.jdl.JdlPackage;
import io.github.jhipster.jdl.dsl.jdl.Relationship;
import io.github.jhipster.jdl.dsl.jdl.RelationshipName;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Relationship</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.github.jhipster.jdl.dsl.jdl.impl.RelationshipImpl#getFromEntity <em>From Entity</em>}</li>
 *   <li>{@link io.github.jhipster.jdl.dsl.jdl.impl.RelationshipImpl#getFromName <em>From Name</em>}</li>
 *   <li>{@link io.github.jhipster.jdl.dsl.jdl.impl.RelationshipImpl#getToEntity <em>To Entity</em>}</li>
 *   <li>{@link io.github.jhipster.jdl.dsl.jdl.impl.RelationshipImpl#getToName <em>To Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RelationshipImpl extends MinimalEObjectImpl.Container implements Relationship
{
  /**
   * The cached value of the '{@link #getFromEntity() <em>From Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFromEntity()
   * @generated
   * @ordered
   */
  protected Entity fromEntity;

  /**
   * The cached value of the '{@link #getFromName() <em>From Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFromName()
   * @generated
   * @ordered
   */
  protected RelationshipName fromName;

  /**
   * The cached value of the '{@link #getToEntity() <em>To Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getToEntity()
   * @generated
   * @ordered
   */
  protected Entity toEntity;

  /**
   * The cached value of the '{@link #getToName() <em>To Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getToName()
   * @generated
   * @ordered
   */
  protected RelationshipName toName;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RelationshipImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JdlPackage.Literals.RELATIONSHIP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entity getFromEntity()
  {
    if (fromEntity != null && fromEntity.eIsProxy())
    {
      InternalEObject oldFromEntity = (InternalEObject)fromEntity;
      fromEntity = (Entity)eResolveProxy(oldFromEntity);
      if (fromEntity != oldFromEntity)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, JdlPackage.RELATIONSHIP__FROM_ENTITY, oldFromEntity, fromEntity));
      }
    }
    return fromEntity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entity basicGetFromEntity()
  {
    return fromEntity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFromEntity(Entity newFromEntity)
  {
    Entity oldFromEntity = fromEntity;
    fromEntity = newFromEntity;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JdlPackage.RELATIONSHIP__FROM_ENTITY, oldFromEntity, fromEntity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RelationshipName getFromName()
  {
    return fromName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFromName(RelationshipName newFromName, NotificationChain msgs)
  {
    RelationshipName oldFromName = fromName;
    fromName = newFromName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JdlPackage.RELATIONSHIP__FROM_NAME, oldFromName, newFromName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFromName(RelationshipName newFromName)
  {
    if (newFromName != fromName)
    {
      NotificationChain msgs = null;
      if (fromName != null)
        msgs = ((InternalEObject)fromName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JdlPackage.RELATIONSHIP__FROM_NAME, null, msgs);
      if (newFromName != null)
        msgs = ((InternalEObject)newFromName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JdlPackage.RELATIONSHIP__FROM_NAME, null, msgs);
      msgs = basicSetFromName(newFromName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JdlPackage.RELATIONSHIP__FROM_NAME, newFromName, newFromName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entity getToEntity()
  {
    if (toEntity != null && toEntity.eIsProxy())
    {
      InternalEObject oldToEntity = (InternalEObject)toEntity;
      toEntity = (Entity)eResolveProxy(oldToEntity);
      if (toEntity != oldToEntity)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, JdlPackage.RELATIONSHIP__TO_ENTITY, oldToEntity, toEntity));
      }
    }
    return toEntity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entity basicGetToEntity()
  {
    return toEntity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setToEntity(Entity newToEntity)
  {
    Entity oldToEntity = toEntity;
    toEntity = newToEntity;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JdlPackage.RELATIONSHIP__TO_ENTITY, oldToEntity, toEntity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RelationshipName getToName()
  {
    return toName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetToName(RelationshipName newToName, NotificationChain msgs)
  {
    RelationshipName oldToName = toName;
    toName = newToName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JdlPackage.RELATIONSHIP__TO_NAME, oldToName, newToName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setToName(RelationshipName newToName)
  {
    if (newToName != toName)
    {
      NotificationChain msgs = null;
      if (toName != null)
        msgs = ((InternalEObject)toName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JdlPackage.RELATIONSHIP__TO_NAME, null, msgs);
      if (newToName != null)
        msgs = ((InternalEObject)newToName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JdlPackage.RELATIONSHIP__TO_NAME, null, msgs);
      msgs = basicSetToName(newToName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JdlPackage.RELATIONSHIP__TO_NAME, newToName, newToName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JdlPackage.RELATIONSHIP__FROM_NAME:
        return basicSetFromName(null, msgs);
      case JdlPackage.RELATIONSHIP__TO_NAME:
        return basicSetToName(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JdlPackage.RELATIONSHIP__FROM_ENTITY:
        if (resolve) return getFromEntity();
        return basicGetFromEntity();
      case JdlPackage.RELATIONSHIP__FROM_NAME:
        return getFromName();
      case JdlPackage.RELATIONSHIP__TO_ENTITY:
        if (resolve) return getToEntity();
        return basicGetToEntity();
      case JdlPackage.RELATIONSHIP__TO_NAME:
        return getToName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JdlPackage.RELATIONSHIP__FROM_ENTITY:
        setFromEntity((Entity)newValue);
        return;
      case JdlPackage.RELATIONSHIP__FROM_NAME:
        setFromName((RelationshipName)newValue);
        return;
      case JdlPackage.RELATIONSHIP__TO_ENTITY:
        setToEntity((Entity)newValue);
        return;
      case JdlPackage.RELATIONSHIP__TO_NAME:
        setToName((RelationshipName)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JdlPackage.RELATIONSHIP__FROM_ENTITY:
        setFromEntity((Entity)null);
        return;
      case JdlPackage.RELATIONSHIP__FROM_NAME:
        setFromName((RelationshipName)null);
        return;
      case JdlPackage.RELATIONSHIP__TO_ENTITY:
        setToEntity((Entity)null);
        return;
      case JdlPackage.RELATIONSHIP__TO_NAME:
        setToName((RelationshipName)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JdlPackage.RELATIONSHIP__FROM_ENTITY:
        return fromEntity != null;
      case JdlPackage.RELATIONSHIP__FROM_NAME:
        return fromName != null;
      case JdlPackage.RELATIONSHIP__TO_ENTITY:
        return toEntity != null;
      case JdlPackage.RELATIONSHIP__TO_NAME:
        return toName != null;
    }
    return super.eIsSet(featureID);
  }

} //RelationshipImpl
