/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.dsl.jdl.impl;

import io.github.jhipster.jdl.dsl.jdl.JdlPackage;
import io.github.jhipster.jdl.dsl.jdl.ZonedDateTimeField;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Zoned Date Time Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ZonedDateTimeFieldImpl extends DateFieldImpl implements ZonedDateTimeField
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ZonedDateTimeFieldImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JdlPackage.Literals.ZONED_DATE_TIME_FIELD;
  }

} //ZonedDateTimeFieldImpl
