/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package ch.itemis.xdocker.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class XdockerIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new XdockerStandaloneSetupIdea().createInjector
	}

}
