/*
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.idea.lang


class JDLFileType extends AbstractJDLFileType {
	public static final JDLFileType INSTANCE = new JDLFileType()
	
	new() {
		super(JDLLanguage.INSTANCE)
	}
}
