/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package ch.itemis.xdocker.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
class XdockerOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
