/*
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.web

/**
 * Use this class to register additional components to be used within the web application.
 */
//@FinalFieldsConstructor
class JDLWebModule extends AbstractJDLWebModule {
}
