<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>*.jdl,*.jh</string>
	</array>
	<key>name</key>
	<string>jdl</string>
	<key>patterns</key>
	<array>
        <!-- application -->
        <dict>
            <key>begin</key>
			<string>(application)\s+</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.modifier.java</string>
                </dict>
            </dict>
			<key>end</key>
            <string>}</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>source.java#comments</string>
                </dict>
                <dict>
                	<key>match</key>
                    <string>\b(config)\b</string>
					<key>end</key>
        		    <string>}</string>
                    <key>name</key>
                    <string>storage.modifier.java</string>
                </dict>
            </array>
        </dict>
        <!-- deployment -->
        <dict>
            <key>include</key>
            <string>source.java#comments</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(deployment)\b</string>
            <key>end</key>
            <string>}</string>
            <key>name</key>
            <string>storage.modifier.java</string>
        </dict>
        <!-- enums -->
        <dict>
            <key>begin</key>
			<string>(enum)\s+(\w+)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.modifier.java</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.class.java</string>
                </dict>
            </dict>
			<key>end</key>
            <string>}</string>
            <key>name</key>
            <string>meta.enum.jdl</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>source.java#comments</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>source.java#enums</string>
                </dict>
            </array>
        </dict>
        <!-- entities -->
        <dict>
            <key>begin</key>
			<string>(entity)\s+(\w+)(\s*\(\s*(\w+)\s*\))?</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.modifier.java</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.class.java</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>variable.parameter.java</string>
                </dict>
            </dict>
			<key>end</key>
            <string>(}|$)</string>
            <key>name</key>
            <string>meta.entity.jdl</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>\b(\w+)\s+([A-Z]+\w*)</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>variable.parameter.java</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.type.class.java</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>(,|\}|$)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.java#comments</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>source.java#constants-and-special-vars</string>
                        </dict>
                        <dict>
                            <key>match</key>
                            <string>\b(required|min|max|minlength|maxlength|minbytes|maxbytes|pattern)\b</string>
                            <key>name</key>
                            <string>storage.modifier.java</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>include</key>
                    <string>source.java#comments</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>include</key>
            <string>source.java#comments</string>
        </dict>
        <!-- relationships -->
        <dict>
            <key>begin</key>
			<string>(relationship)\s+(ManyToMany|ManyToOne|OneToMany|OneToOne)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.modifier.java</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>storage.modifier.java</string>
                </dict>
            </dict>
			<key>end</key>
            <string>}</string>
            <key>name</key>
            <string>meta.relationship.jdl</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>source.java#comments</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(([A-Z]\w*)(\s*\{(\s*\w+\s*)(\s*\((\s*\w+\s*)\))?\s*(required)?\s*\})?)</string>
                    <key>captures</key>
                    <dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.type.class.java</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>variable.parameter.java</string>
                        </dict>
                        <key>6</key>
                        <dict>
                            <key>name</key>
                            <string>variable.parameter.java</string>
                        </dict>
                        <key>7</key>
                        <dict>
                            <key>name</key>
                            <string>storage.modifier.java</string>
                        </dict>
                    </dict>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\bto\b</string>
                    <key>name</key>
                    <string>keyword.control.java</string>
                </dict>
            </array>
        </dict>
        <!-- unary options -->
        <dict>
            <key>match</key>
            <string>\b(noFluentMethod|skipClient|skipServer)\s+(for)\s+(([A-Z]\w*\s*),\s*)*([A-Z]\w*|\*|all)(\s+(except)\s+(([A-Z]\w*\s*),\s*)*([A-Z]\w*))?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>>storage.modifier.java</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.java</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.class.java</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.class.java</string>
                </dict>
                <key>7</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.java</string>
                </dict>
                <key>9</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.class.java</string>
                </dict>
                <key>10</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.class.java</string>
                </dict>
            </dict>
        </dict>
        <!-- binary options -->
        <dict>
            <key>match</key>
            <string>\b(angularSuffix|dto|microservice|paginate|search|service)\s+(([A-Z]\w*\s*),\s*)*([A-Z]\w*|\*|all)(\s+(with)\s+([a-zA-Z_\-0-9]+)(\s+(except)\s+(([A-Z]\w*\s*),\s*)*([A-Z]\w*))?)?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>>storage.modifier.java</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.class.java</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.class.java</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.java</string>
                </dict>
                <key>7</key>
                <dict>
                    <key>name</key>
                    <string>variable.parameter.java</string>
                </dict>
                <key>9</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.java</string>
                </dict>
                <key>11</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.class.java</string>
                </dict>
                <key>12</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.class.java</string>
                </dict>
            </dict>
        </dict>
	</array>
	<key>scopeName</key>
	<string>text.jdl</string>
</dict>
</plist>
