/*
 * generated by Xtext 2.11.0
 */
package ch.itemis.xdocker.ide

import ch.itemis.xdocker.XdockerRuntimeModule
import ch.itemis.xdocker.XdockerStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class XdockerIdeSetup extends XdockerStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new XdockerRuntimeModule, new XdockerIdeModule))
	}
	
}
