/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package ch.itemis.xdocker.web

/**
 * Use this class to register additional components to be used within the web application.
 */
class XdockerWebModule extends AbstractXdockerWebModule {
}
