/*
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.dsl.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractJDLCompletionContributor extends TerminalsCompletionContributor {
	public AbstractJDLCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
