/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.dsl.ui;

import io.github.jhipster.jdl.dsl.ui.AbstractJDLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class JDLUiModule extends AbstractJDLUiModule {
  public JDLUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
