/*
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.dsl.idea.lang.psi;

import com.intellij.psi.util.PsiModificationTracker;
import io.github.jhipster.jdl.dsl.idea.lang.JDLLanguage;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;

public class JDLCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public JDLCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(JDLLanguage.INSTANCE, psiModificationTracker);
	}

}
