/**
 * Copyright 2013-2018 the original author or authors from the JHipster project.
 * 
 * This file is part of the JHipster project, see http://www.jhipster.tech/
 * for more information.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.jhipster.jdl.tests

import com.google.inject.Inject
import com.google.inject.Injector
import com.google.inject.Provider
import io.github.jhipster.jdl.JDLStandaloneSetup
import java.io.File
import java.nio.file.Files
import java.nio.file.Paths
import java.util.Collection
import java.util.Set
import org.eclipse.emf.common.util.URI
import org.eclipse.emf.ecore.resource.ResourceSet
import org.eclipse.xtend.lib.annotations.Data
import org.eclipse.xtext.diagnostics.Severity
import org.eclipse.xtext.generator.IGenerator2
import org.eclipse.xtext.generator.JavaIoFileSystemAccess
import org.eclipse.xtext.util.CancelIndicator
import org.eclipse.xtext.validation.CheckMode
import org.eclipse.xtext.validation.IResourceValidator
import org.eclipse.xtext.validation.Issue
import org.junit.AfterClass
import org.junit.Before
import org.junit.BeforeClass
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.Parameterized
import org.junit.runners.Parameterized.Parameters

import static org.eclipse.xtext.diagnostics.Severity.*
import static org.junit.Assert.*

/**
 * @author Serano Colameo - Initial contribution and API
 */
@RunWith(Parameterized)
class JDLFileTest {

	@Inject Provider<ResourceSet> resourceSetProvider;
	@Inject IResourceValidator validator;
	@Inject IGenerator2 generator;
	@Inject JavaIoFileSystemAccess fileAccess;

	var ResourceSet resourceSet
	var File jdlFile
	var Injector injector

	static Set<File> jdlReferencedFiles
	static Set<Pair<File, Issue>> unexpectedIssues
	
	@Data
	static class JdlIssue {
		String message
		Severity sevirity
	}
	
	val expectedIssues = #[
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"for_keyword_notallowed.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"useless_table_names.jdl" -> new JdlIssue('Definition has no effect. Remove superfluous table name or define a different name.', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_enum_values.jdl" -> new JdlIssue('Enum value name must be upper case', ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"different_relationship_types.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"21-points.jh" -> new JdlIssue("Duplicate JdlDisplayField 'login' in JdlRelationRole 'user'", ERROR),
		"user_entity_to_relationship.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"cassandra_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"no_injected_field.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'department'", ERROR),
		"ex10.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'a'", ERROR),
		"wrong_required_relationships_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"simple-online-shop.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"user_entity_from_relationship.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"different_relationship_types.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"ex29.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"duplicate_enums.jdl" -> new JdlIssue('Unused enum definition in "duplicate_enums.jdl"', INFO),
		"for_keyword_notallowed.jdl" -> new JdlIssue("mismatched input '<EOF>' expecting '='", ERROR),
		"21-points.jh" -> new JdlIssue("Duplicate JdlDisplayField 'login' in JdlRelationRole 'user'", ERROR),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl_2.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"simple-online-shop.jh" -> new JdlIssue('Found groupable relationship "ManyToMany"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"ex25.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"21-points.jh" -> new JdlIssue("Duplicate JdlRelationRole 'user'", ERROR),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"useless_commas_fields.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"ex21.jdl" -> new JdlIssue('Entity declaration can be shorten to "entity MySecondEntity"', INFO),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"ex10.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'c'", ERROR),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "ManyToMany"', WARNING),
		"two_microservices.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"ex28.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"cassandra_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl_2.jdl" -> new JdlIssue('Entity declaration can be shorten to "entity B"', INFO),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"for_keyword_notallowed.jdl" -> new JdlIssue("Duplicate JdlFeature 'Region' in JdlDomainModel 'for_keyword_notallowed'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"for_keyword_notallowed.jdl" -> new JdlIssue("Couldn't resolve reference to JdlEntity 'for'.", ERROR),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"realistic_sample.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"ex11.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'department'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"ungrouped_relationships.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"ex26.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"bug-tracker.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"microservice-ecommerce-store-k8s.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"different_relationship_types.jdl" -> new JdlIssue('Found groupable relationship "ManyToMany"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"bug-tracker.jh" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"online-shop.jh" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"simple-online-shop.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'department'", ERROR),
		"duration_type.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"microservices-blog-store.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"multiple_jdl_comments.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"for_keyword_notallowed.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"simple-online-shop.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Field [jobTitle1] does not exist in entity [Job]', WARNING),
		"cassandra_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"mongo_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"good_pattern_definition.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"good_pattern_definition.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"for_keyword_notallowed.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"jdl2.jdl" -> new JdlIssue('Unused enum definition in "jdl2.jdl"', INFO),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"big_sample.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'department'", ERROR),
		"intant_type.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"unique.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"microservice-ecommerce-store-k8s.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"21-points.jh" -> new JdlIssue("Duplicate JdlRelationRole 'user'", ERROR),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'department'", ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"online-shop.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"big_sample.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'department'", ERROR),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"duplicate_enums.jdl" -> new JdlIssue("Duplicate JdlFeature 'A' in JdlDomainModel 'duplicate_enums'", ERROR),
		"multiple_jdl_comments.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"21-points.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"unused_enums.jdl" -> new JdlIssue('Unused enum definition in "unused_enums.jdl"', INFO),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"two_microservices.jdl" -> new JdlIssue('Definition has no effect. Remove superfluous table name or define a different name.', WARNING),
		"microservice-ecommerce-store-4-apps.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_relationships_jdl.jdl" -> new JdlIssue("mismatched input '}' expecting RULE_ID", ERROR),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"mongo_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"ungrouped_relationships.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"cassandra_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"no_injected_field.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"microservice-ecommerce-store-k8s.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'order'", ERROR),
		"duration_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"duplicate_entities.jdl" -> new JdlIssue("Duplicate JdlFeature 'A' in JdlDomainModel 'duplicate_entities'", ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_pattern_definition.jdl" -> new JdlIssue('Wrong regexp pattern!', ERROR),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"cassandra_with_relationships.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"big_sample.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToMany"', WARNING),
		"microservice-ecommerce-store.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"filtering_validation_check.jdl" -> new JdlIssue('Selection does not contain excluded elements: [C, D]', ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_enum_values.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"for_keyword_notallowed.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"application_with_duplicate_params.jdl" -> new JdlIssue('Parameter [enableTranslation] already defined!', ERROR),
		"Model.jdl" -> new JdlIssue("Duplicate JdlEntityField 'a'", ERROR),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"online-shop.jh" -> new JdlIssue('Found groupable relationship "ManyToMany"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"intant_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"wrong_required_relationships_jdl.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'c'", ERROR),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_enum_values.jdl" -> new JdlIssue('Enum value name must be upper case', ERROR),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_pattern_definition.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"simple.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"online-shop.jh" -> new JdlIssue("Duplicate JdlDisplayField 'title' in JdlRelationRole 'product'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_relationships_jdl.jdl" -> new JdlIssue("mismatched input '<EOF>' expecting '}'", ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"following_comments.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"for_keyword_notallowed.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"table.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"invalid_field_type.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"big_sample.jdl" -> new JdlIssue('Field [region] does not exist in entity [Region]', WARNING),
		"realistic_sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl_2.jdl" -> new JdlIssue('Entity declaration can be shorten to "entity E"', INFO),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"couchbase_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duplicate_fields.jdl" -> new JdlIssue("Duplicate JdlEntityField 'aa'", ERROR),
		"21-points.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"ex10.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'c'", ERROR),
		"microservice-ecommerce-store-4-apps.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"blog.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"mongo_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"microservice-ecommerce-store-k8s.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"microservice-ecommerce-store-4-apps.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"21-points.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"microservice-ecommerce-store-k8s.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"required_relationships.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"microservice-ecommerce-store.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"ex10.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'd'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"ungrouped_relationships.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"big_sample.jdl" -> new JdlIssue("Duplicate JdlDisplayField 'employee' in JdlRelationRole 'emp'", ERROR),
		"21-points.jh" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"enum.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"invalid_field_type.jdl" -> new JdlIssue("Couldn't resolve reference to JdlEnum 'NullPointerException'.", ERROR),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"microservice-ecommerce-store.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'product'", ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "ManyToMany"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"microservice-ecommerce-store.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'order'", ERROR),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"microservice-ecommerce-store.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"duplicate_deployments.jdl" -> new JdlIssue('Parameter [deploymentType] already defined!', ERROR),
		"couchbase_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"simple.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"bug-tracker.jh" -> new JdlIssue("Duplicate JdlRelationRole 'ticket'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"microservice-ecommerce-store-k8s.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'product'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"mongo_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"microservice-ecommerce-store.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'product'", ERROR),
		"mongo_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"two_microservices.jdl" -> new JdlIssue('Definition has no effect. Remove superfluous table name or define a different name.', WARNING),
		"cassandra_with_relationships.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_relationships_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"ex30.jdl" -> new JdlIssue('Found groupable relationship "ManyToMany"', WARNING),
		"realistic_sample.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duplicate_enums.jdl" -> new JdlIssue("Duplicate JdlFeature 'A' in JdlDomainModel 'duplicate_enums'", ERROR),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"ex26.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"online-shop.jh" -> new JdlIssue("Duplicate JdlRelationRole 'wishList'", ERROR),
		"cassandra_with_relationships.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duplicate_entities.jdl" -> new JdlIssue("Duplicate JdlFeature 'A' in JdlDomainModel 'duplicate_entities'", ERROR),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"realistic_sample.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_required_relationships_jdl.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'c'", ERROR),
		"intant_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"microservice-ecommerce-store-4-apps.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"online-shop.jh" -> new JdlIssue("Duplicate JdlRelationRole 'customer'", ERROR),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"couchbase_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"ex08.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"couchbase_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"microservices-blog-store.jh" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"for_keyword_notallowed.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"Model.jdl" -> new JdlIssue('Entity declaration can be shorten to "entity Aasas0"', INFO),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"good_pattern_definition.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"blog.jh" -> new JdlIssue('Found groupable relationship "ManyToMany"', WARNING),
		"complex_jdl_2.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"no_comma_support.jdl" -> new JdlIssue('Entity declaration can be shorten to "entity E"', INFO),
		"duplicate_entities.jdl" -> new JdlIssue("Duplicate JdlFeature 'A' in JdlDomainModel 'duplicate_entities'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_pattern_definition.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"realistic_sample.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"for_keyword_notallowed.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"blog.jh" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"good_pattern_definition.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"for_keyword_notallowed.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"duplicate_application_params.jdl" -> new JdlIssue('Parameter [devDatabaseType] already defined!', ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"good_pattern_definition.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"simple-online-shop.jh" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"Model.jdl" -> new JdlIssue("Duplicate JdlEntityField 'a'", ERROR),
		"cassandra_with_relationships.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"microservice-ecommerce-store-k8s.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"microservice-ecommerce-store-4-apps.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'product'", ERROR),
		"wrong_required_relationships_jdl.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'b'", ERROR),
		"microservices-blog-store.jh" -> new JdlIssue('Found groupable relationship "ManyToMany"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "ManyToMany"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"realistic_sample.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"21-points.jh" -> new JdlIssue("Duplicate JdlRelationRole 'user'", ERROR),
		"valid_jdl.jdl" -> new JdlIssue('Entity declaration can be shorten to "entity B"', INFO),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"microservice-ecommerce-store.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"for_keyword_notallowed.jdl" -> new JdlIssue("Duplicate JdlFeature 'Region' in JdlDomainModel 'for_keyword_notallowed'", ERROR),
		"ungrouped_relationships.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"ex09.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"couchbase_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"duplicate_entities.jdl" -> new JdlIssue("Duplicate JdlFeature 'B' in JdlDomainModel 'duplicate_entities'", ERROR),
		"duration_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"ex21.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"online-shop.jh" -> new JdlIssue("Duplicate JdlRelationRole 'customer'", ERROR),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"ex10.jdl" -> new JdlIssue('Found groupable relationship "ManyToMany"', WARNING),
		"big_sample.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'emp'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_required_relationships_jdl.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'b'", ERROR),
		"microservice-ecommerce-store-4-apps.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"unexistent_entities_for_relationship.jdl" -> new JdlIssue("Couldn't resolve reference to JdlEntity 'B'.", ERROR),
		"microservice-ecommerce-store.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'order'", ERROR),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Field [title1] does not exist in entity [Task]', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'department'", ERROR),
		"duration_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'department'", ERROR),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"21-points.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"mongo_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"duplicate_enums.jdl" -> new JdlIssue('Duplicate enum value "BA"', ERROR),
		"realistic_sample.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"cassandra_with_relationships.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"duration_type.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"good_pattern_definition.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"microservice-ecommerce-store-k8s.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'order'", ERROR),
		"mongo_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"good_pattern_definition.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"non_existent_validation.jdl" -> new JdlIssue("mismatched input 'min' expecting '}'", ERROR),
		"big_sample.jdl" -> new JdlIssue('Field [employee] does not exist in entity [Employee]', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"21-points.jh" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"duplicate_fields.jdl" -> new JdlIssue("Duplicate JdlEntityField 'cc'", ERROR),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"realistic_sample.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'product'", ERROR),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"microservice-ecommerce-store-k8s.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"online-shop.jh" -> new JdlIssue("Duplicate JdlDisplayField 'title' in JdlRelationRole 'product'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_required_relationships_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"microservice-ecommerce-store-4-apps.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_pattern_definition.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_required_relationships_jdl.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'd'", ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"filtering_validation_check.jdl" -> new JdlIssue('Selection does not contain excluded elements: [C, D]', ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"no_injected_field.jdl" -> new JdlIssue('Found groupable relationship "ManyToMany"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"ex10.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'd'", ERROR),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"ex10.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"couchbase_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"user_entity_to_relationship.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duplicate_entities.jdl" -> new JdlIssue("Duplicate JdlFeature 'B' in JdlDomainModel 'duplicate_entities'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"ex24.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"big_sample.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"big_sample.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'emp'", ERROR),
		"duration_type.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"intant_type.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"ex26.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"21-points.jh" -> new JdlIssue("Duplicate JdlDisplayField 'login' in JdlRelationRole 'user'", ERROR),
		"duration_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "ManyToMany"', WARNING),
		"cassandra_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"realistic_sample.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'product'", ERROR),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"unexistent_entities_for_relationship.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"simple-online-shop.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"big_sample.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"ungrouped_relationships.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"big_sample.jdl" -> new JdlIssue('Found groupable relationship "ManyToMany"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"microservices-blog-store.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"good_pattern_definition.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"cassandra_with_relationships.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"id_field.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'department'", ERROR),
		"bug-tracker.jh" -> new JdlIssue("Duplicate JdlRelationRole 'ticket'", ERROR),
		"ungrouped_relationships.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"ex10.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'a'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"realistic_sample.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"couchbase_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'department'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_required_relationships_jdl.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"invalid_option.jdl" -> new JdlIssue("missing 'mapstruct' at 'wrong'", ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"big_sample.jdl" -> new JdlIssue('Field [JobTitle] does not exist in entity [Job]', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"two_microservices.jdl" -> new JdlIssue('Definition has no effect. Remove superfluous table name or define a different name.', WARNING),
		"microservice-ecommerce-store-4-apps.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'product'", ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"big_sample.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"ungrouped_relationships.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"useless_table_names.jdl" -> new JdlIssue('Definition has no effect. Remove superfluous table name or define a different name.', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duplicate_enums.jdl" -> new JdlIssue('Unused enum definition in "duplicate_enums.jdl"', INFO),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"microservice-ecommerce-store-4-apps.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"big_sample.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"online-shop.jh" -> new JdlIssue("Duplicate JdlRelationRole 'wishList'", ERROR),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"online-shop.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_pattern_definition.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"intant_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"duration_type.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_pattern_definition.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"online-shop.jh" -> new JdlIssue("Duplicate JdlRelationRole 'product'", ERROR),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"microservice-ecommerce-store.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"cassandra_with_relationships.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToMany"', WARNING),
		"wrong_pattern_definition.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"duplicate_enums.jdl" -> new JdlIssue('Unused enum definition in "duplicate_enums.jdl"', INFO),
		"wrong_pattern_definition.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_required_relationships_jdl.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'd'", ERROR),
		"duplicate_fields.jdl" -> new JdlIssue("Duplicate JdlEntityField 'cc'", ERROR),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"cassandra_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"user_entity_to_relationship.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'user'", ERROR),
		"microservice-ecommerce-store.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"simple-online-shop.jh" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"different_relationship_types.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"microservice-ecommerce-store-4-apps.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"microservice-ecommerce-store-k8s.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"no_comma_support.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"big_sample.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"big_sample.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"ungrouped_relationships.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"online-shop.jh" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"big_sample.jdl" -> new JdlIssue("Duplicate JdlDisplayField 'employee' in JdlRelationRole 'emp'", ERROR),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'department'", ERROR),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_pattern_definition.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"cassandra_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"ex27.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"microservices-blog-store.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"intant_type.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"duplicate_fields.jdl" -> new JdlIssue("Duplicate JdlEntityField 'aa'", ERROR),
		"relationship_jpa_derived_identifier.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"microservice-ecommerce-store.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"cassandra_with_relationships.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"online-shop.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"microservice-ecommerce-store-k8s.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'product'", ERROR),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"online-shop.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"couchbase_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"bug-tracker.jh" -> new JdlIssue('Found groupable relationship "ManyToMany"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"online-shop.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"big_sample.jdl" -> new JdlIssue('Field [employee] does not exist in entity [Employee]', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"big_sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"cassandra_with_relationships.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"useless_table_names.jdl" -> new JdlIssue('Definition has no effect. Remove superfluous table name or define a different name.', WARNING),
		"ungrouped_relationships.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"wrong_required_relationships_jdl.jdl" -> new JdlIssue('Found groupable relationship "ManyToMany"', WARNING),
		"blob_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"no_comma_support.jdl" -> new JdlIssue('Entity declaration can be shorten to "entity B"', INFO),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"blog.jh" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"complex_jdl.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"21-points.jh" -> new JdlIssue("Duplicate JdlDisplayField 'login' in JdlRelationRole 'user'", ERROR),
		"big_sample.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"two_microservices.jdl" -> new JdlIssue('Definition has no effect. Remove superfluous table name or define a different name.', WARNING),
		"big_sample.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"mongo_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"online-shop.jh" -> new JdlIssue("Duplicate JdlRelationRole 'product'", ERROR),
		"unused_enums.jdl" -> new JdlIssue('Unused enum definition in "unused_enums.jdl"', INFO),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"big_sample.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"complex_jdl.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"pattern_validation_with_quote.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"21-points.jh" -> new JdlIssue("Duplicate JdlRelationRole 'user'", ERROR),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"complex_jdl.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'department'", ERROR),
		"microservice-ecommerce-store-k8s.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"valid_jdl.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"user_entity_to_relationship.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'user'", ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duplicate_relationships.jdl" -> new JdlIssue('Relationship [A->B] already defined!', ERROR),
		"microservice-ecommerce-store.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"intant_type.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"ex12.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"Oracle-Human-Resources-sample.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'job'", ERROR),
		"duration_type.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"duplicate_relationships.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"ex26.jdl" -> new JdlIssue('Found groupable relationship "OneToOne"', WARNING),
		"cassandra_jdl.jdl" -> new JdlIssue('Useless commas can be removed', WARNING),
		"intant_type.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"wrong_displayfield_in_source.jdl" -> new JdlIssue("Duplicate JdlRelationRole 'employee'", ERROR),
		"wrong_displayfield_in_target.jdl" -> new JdlIssue('Found groupable relationship "OneToMany"', WARNING),
		"ex07.jdl" -> new JdlIssue('Found groupable relationship "ManyToOne"', WARNING),
		"useless_entity_curly_braces.jdl" -> new JdlIssue('Entity declaration can be shorten to "entity B"', INFO)
	]

	new(File jdlFile) {
		this.jdlFile = jdlFile
	}

	@BeforeClass
	def static void initTestCase() {
		unexpectedIssues = newHashSet
		// put here all JDL definitions which are referenced by other JDLs
		jdlReferencedFiles = #{
			new File('./resources/test_files/jdl2.jdl')
		}
	}

	@AfterClass
	def static void reportIssues() {
		unexpectedIssues.forEach [ issue |
			val msgtoken = if(issue.value.message.contains("'")) '"' else "'"
			System.err.println('''"«issue.key.name»" -> new JdlIssue(«msgtoken»«issue.value.message»«msgtoken», «issue.value.severity»),''')
		]
		if(unexpectedIssues.isEmpty == false) fail('Unexpected issues found! Check output...')
	}

	@Before
	def void setUp() {
		injector = new JDLStandaloneSetup().createInjectorAndDoEMFRegistration()
		injector.injectMembers(this)
		resourceSet = resourceSetProvider.get
	}

	@Parameters
	def static Collection<File> getJdlFiles() {
		val result = newArrayList
		Files.walk(
			Paths.get('./resources/')
		).filter [
			Files.isDirectory(it)
		].map [
			it.toFile.listFiles([ dir, name |
				name.endsWith('.jdl') || name.endsWith('.jh')
			])
		].forEach[result.addAll(it)]
		return result
	}

	@Test
	def void testJdlFile() {
		jdlReferencedFiles.forEach [
			resourceSet.getResource(URI.createURI(absoluteFile.toURI.toString), true)
		]
		println('''Load and validate «jdlFile»''')
		val resource = resourceSet.getResource(URI.createURI(jdlFile.toURI.toString), true)
		// validate the resource
		val issues = validator.validate(resource, CheckMode.ALL, CancelIndicator.NullImpl)
		issues?.forEach [ issue |
			val expected = expectedIssues.findFirst [
				jdlFile.name.equals(key) && value.message.startsWith(issue.message) && value.sevirity == issue.severity
			]
			if (expected !== null)
				println('''Expected issue detected: [«issue»]''')
			else
				unexpectedIssues += jdlFile -> issue
		]
		// configure and start the generator
		fileAccess.setOutputPath("src-gen/");
		try {
			generator.doGenerate(resource, fileAccess, null);
		} catch (Exception ex) {
			println('''Error in «jdlFile»''')
			ex.printStackTrace
			throw ex
		}
	}
}
