/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.jdl.impl;

import io.github.jhipster.jdl.jdl.JdlBlobFieldType;
import io.github.jhipster.jdl.jdl.JdlFieldType;
import io.github.jhipster.jdl.jdl.JdlPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Field Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.github.jhipster.jdl.jdl.impl.JdlFieldTypeImpl#getBlobFieldType <em>Blob Field Type</em>}</li>
 *   <li>{@link io.github.jhipster.jdl.jdl.impl.JdlFieldTypeImpl#getValidators <em>Validators</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JdlFieldTypeImpl extends MinimalEObjectImpl.Container implements JdlFieldType
{
  /**
   * The default value of the '{@link #getBlobFieldType() <em>Blob Field Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBlobFieldType()
   * @generated
   * @ordered
   */
  protected static final JdlBlobFieldType BLOB_FIELD_TYPE_EDEFAULT = JdlBlobFieldType.BLOB;

  /**
   * The cached value of the '{@link #getBlobFieldType() <em>Blob Field Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBlobFieldType()
   * @generated
   * @ordered
   */
  protected JdlBlobFieldType blobFieldType = BLOB_FIELD_TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getValidators() <em>Validators</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValidators()
   * @generated
   * @ordered
   */
  protected EObject validators;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JdlFieldTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JdlPackage.Literals.JDL_FIELD_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public JdlBlobFieldType getBlobFieldType()
  {
    return blobFieldType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBlobFieldType(JdlBlobFieldType newBlobFieldType)
  {
    JdlBlobFieldType oldBlobFieldType = blobFieldType;
    blobFieldType = newBlobFieldType == null ? BLOB_FIELD_TYPE_EDEFAULT : newBlobFieldType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JdlPackage.JDL_FIELD_TYPE__BLOB_FIELD_TYPE, oldBlobFieldType, blobFieldType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EObject getValidators()
  {
    return validators;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetValidators(EObject newValidators, NotificationChain msgs)
  {
    EObject oldValidators = validators;
    validators = newValidators;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JdlPackage.JDL_FIELD_TYPE__VALIDATORS, oldValidators, newValidators);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValidators(EObject newValidators)
  {
    if (newValidators != validators)
    {
      NotificationChain msgs = null;
      if (validators != null)
        msgs = ((InternalEObject)validators).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JdlPackage.JDL_FIELD_TYPE__VALIDATORS, null, msgs);
      if (newValidators != null)
        msgs = ((InternalEObject)newValidators).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JdlPackage.JDL_FIELD_TYPE__VALIDATORS, null, msgs);
      msgs = basicSetValidators(newValidators, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JdlPackage.JDL_FIELD_TYPE__VALIDATORS, newValidators, newValidators));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JdlPackage.JDL_FIELD_TYPE__VALIDATORS:
        return basicSetValidators(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JdlPackage.JDL_FIELD_TYPE__BLOB_FIELD_TYPE:
        return getBlobFieldType();
      case JdlPackage.JDL_FIELD_TYPE__VALIDATORS:
        return getValidators();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JdlPackage.JDL_FIELD_TYPE__BLOB_FIELD_TYPE:
        setBlobFieldType((JdlBlobFieldType)newValue);
        return;
      case JdlPackage.JDL_FIELD_TYPE__VALIDATORS:
        setValidators((EObject)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JdlPackage.JDL_FIELD_TYPE__BLOB_FIELD_TYPE:
        setBlobFieldType(BLOB_FIELD_TYPE_EDEFAULT);
        return;
      case JdlPackage.JDL_FIELD_TYPE__VALIDATORS:
        setValidators((EObject)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JdlPackage.JDL_FIELD_TYPE__BLOB_FIELD_TYPE:
        return blobFieldType != BLOB_FIELD_TYPE_EDEFAULT;
      case JdlPackage.JDL_FIELD_TYPE__VALIDATORS:
        return validators != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (blobFieldType: ");
    result.append(blobFieldType);
    result.append(')');
    return result.toString();
  }

} //JdlFieldTypeImpl
