/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.jdl.impl;

import io.github.jhipster.jdl.jdl.JdlBlobFieldType;
import io.github.jhipster.jdl.jdl.JdlBlobValidators;
import io.github.jhipster.jdl.jdl.JdlCardinality;
import io.github.jhipster.jdl.jdl.JdlDomainModel;
import io.github.jhipster.jdl.jdl.JdlDtoType;
import io.github.jhipster.jdl.jdl.JdlEntity;
import io.github.jhipster.jdl.jdl.JdlEntityExclusion;
import io.github.jhipster.jdl.jdl.JdlEntityField;
import io.github.jhipster.jdl.jdl.JdlEntityInclusion;
import io.github.jhipster.jdl.jdl.JdlEnumType;
import io.github.jhipster.jdl.jdl.JdlFactory;
import io.github.jhipster.jdl.jdl.JdlFeature;
import io.github.jhipster.jdl.jdl.JdlFieldType;
import io.github.jhipster.jdl.jdl.JdlGenerationSetting;
import io.github.jhipster.jdl.jdl.JdlGenerationSettingType;
import io.github.jhipster.jdl.jdl.JdlMaxBytesValidator;
import io.github.jhipster.jdl.jdl.JdlMaxLengthValidator;
import io.github.jhipster.jdl.jdl.JdlMaxValidator;
import io.github.jhipster.jdl.jdl.JdlMinBytesValidator;
import io.github.jhipster.jdl.jdl.JdlMinLengthValidator;
import io.github.jhipster.jdl.jdl.JdlMinValidator;
import io.github.jhipster.jdl.jdl.JdlNumericFieldType;
import io.github.jhipster.jdl.jdl.JdlNumericValidators;
import io.github.jhipster.jdl.jdl.JdlPackage;
import io.github.jhipster.jdl.jdl.JdlPaginateType;
import io.github.jhipster.jdl.jdl.JdlPatternValidator;
import io.github.jhipster.jdl.jdl.JdlRelationship;
import io.github.jhipster.jdl.jdl.JdlRelationshipName;
import io.github.jhipster.jdl.jdl.JdlRelationships;
import io.github.jhipster.jdl.jdl.JdlRequiredValidator;
import io.github.jhipster.jdl.jdl.JdlServiceType;
import io.github.jhipster.jdl.jdl.JdlStringValidators;
import io.github.jhipster.jdl.jdl.JdlWildcardPredicate;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class JdlPackageImpl extends EPackageImpl implements JdlPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlDomainModelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlFeatureEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlEntityEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlEntityFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlFieldTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlStringValidatorsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlNumericValidatorsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlBlobValidatorsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlRequiredValidatorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlMinLengthValidatorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlMaxLengthValidatorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlPatternValidatorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlMinValidatorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlMaxValidatorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlMinBytesValidatorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlMaxBytesValidatorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlRelationshipsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlRelationshipEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlRelationshipNameEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlEnumTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlGenerationSettingEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlGenerationSettingTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlEntityInclusionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlEntityExclusionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlWildcardPredicateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jdlPaginateTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum jdlNumericFieldTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum jdlBlobFieldTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum jdlCardinalityEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum jdlServiceTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum jdlDtoTypeEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see io.github.jhipster.jdl.jdl.JdlPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private JdlPackageImpl()
  {
    super(eNS_URI, JdlFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link JdlPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static JdlPackage init()
  {
    if (isInited) return (JdlPackage)EPackage.Registry.INSTANCE.getEPackage(JdlPackage.eNS_URI);

    // Obtain or create and register package
    JdlPackageImpl theJdlPackage = (JdlPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof JdlPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new JdlPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theJdlPackage.createPackageContents();

    // Initialize created meta-data
    theJdlPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theJdlPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(JdlPackage.eNS_URI, theJdlPackage);
    return theJdlPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlDomainModel()
  {
    return jdlDomainModelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlDomainModel_Features()
  {
    return (EReference)jdlDomainModelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlFeature()
  {
    return jdlFeatureEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlEntity()
  {
    return jdlEntityEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlEntity_Name()
  {
    return (EAttribute)jdlEntityEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlEntity_Fields()
  {
    return (EReference)jdlEntityEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlEntityField()
  {
    return jdlEntityFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlEntityField_Name()
  {
    return (EAttribute)jdlEntityFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlEntityField_Type()
  {
    return (EReference)jdlEntityFieldEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlEntityField_EnumType()
  {
    return (EReference)jdlEntityFieldEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlEntityField_StringType()
  {
    return (EAttribute)jdlEntityFieldEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlEntityField_NumericFieldType()
  {
    return (EAttribute)jdlEntityFieldEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlEntityField_BooleanType()
  {
    return (EAttribute)jdlEntityFieldEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlEntityField_LocalDateType()
  {
    return (EAttribute)jdlEntityFieldEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlEntityField_ZonedDateTimeType()
  {
    return (EAttribute)jdlEntityFieldEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlFieldType()
  {
    return jdlFieldTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlFieldType_BlobFieldType()
  {
    return (EAttribute)jdlFieldTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlFieldType_Validators()
  {
    return (EReference)jdlFieldTypeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlStringValidators()
  {
    return jdlStringValidatorsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlStringValidators_Required()
  {
    return (EAttribute)jdlStringValidatorsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlStringValidators_MinLength()
  {
    return (EReference)jdlStringValidatorsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlStringValidators_Maxlength()
  {
    return (EReference)jdlStringValidatorsEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlStringValidators_Pattern()
  {
    return (EReference)jdlStringValidatorsEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlNumericValidators()
  {
    return jdlNumericValidatorsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlNumericValidators_Required()
  {
    return (EReference)jdlNumericValidatorsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlNumericValidators_Minlength()
  {
    return (EReference)jdlNumericValidatorsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlNumericValidators_Maxlength()
  {
    return (EReference)jdlNumericValidatorsEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlBlobValidators()
  {
    return jdlBlobValidatorsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlBlobValidators_Required()
  {
    return (EReference)jdlBlobValidatorsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlBlobValidators_Minbytes()
  {
    return (EReference)jdlBlobValidatorsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlBlobValidators_Maxbytes()
  {
    return (EReference)jdlBlobValidatorsEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlRequiredValidator()
  {
    return jdlRequiredValidatorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlRequiredValidator_Required()
  {
    return (EAttribute)jdlRequiredValidatorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlMinLengthValidator()
  {
    return jdlMinLengthValidatorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlMinLengthValidator_Value()
  {
    return (EAttribute)jdlMinLengthValidatorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlMaxLengthValidator()
  {
    return jdlMaxLengthValidatorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlMaxLengthValidator_Value()
  {
    return (EAttribute)jdlMaxLengthValidatorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlPatternValidator()
  {
    return jdlPatternValidatorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlPatternValidator_Value()
  {
    return (EAttribute)jdlPatternValidatorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlMinValidator()
  {
    return jdlMinValidatorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlMinValidator_Value()
  {
    return (EAttribute)jdlMinValidatorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlMaxValidator()
  {
    return jdlMaxValidatorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlMaxValidator_Value()
  {
    return (EAttribute)jdlMaxValidatorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlMinBytesValidator()
  {
    return jdlMinBytesValidatorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlMinBytesValidator_Value()
  {
    return (EAttribute)jdlMinBytesValidatorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlMaxBytesValidator()
  {
    return jdlMaxBytesValidatorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlMaxBytesValidator_Value()
  {
    return (EAttribute)jdlMaxBytesValidatorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlRelationships()
  {
    return jdlRelationshipsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlRelationships_Cardinality()
  {
    return (EAttribute)jdlRelationshipsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlRelationships_Relationships()
  {
    return (EReference)jdlRelationshipsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlRelationship()
  {
    return jdlRelationshipEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlRelationship_FromEntity()
  {
    return (EReference)jdlRelationshipEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlRelationship_FromName()
  {
    return (EReference)jdlRelationshipEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlRelationship_ToEntity()
  {
    return (EReference)jdlRelationshipEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlRelationship_ToName()
  {
    return (EReference)jdlRelationshipEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlRelationshipName()
  {
    return jdlRelationshipNameEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlRelationshipName_Name()
  {
    return (EAttribute)jdlRelationshipNameEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlRelationshipName_Role()
  {
    return (EAttribute)jdlRelationshipNameEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlEnumType()
  {
    return jdlEnumTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlEnumType_Name()
  {
    return (EAttribute)jdlEnumTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlEnumType_Values()
  {
    return (EAttribute)jdlEnumTypeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlGenerationSetting()
  {
    return jdlGenerationSettingEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlGenerationSetting_Setting()
  {
    return (EReference)jdlGenerationSettingEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlGenerationSetting_Excludes()
  {
    return (EReference)jdlGenerationSettingEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlGenerationSetting_ServiceGenerationSetting()
  {
    return (EAttribute)jdlGenerationSettingEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlGenerationSetting_Includes()
  {
    return (EReference)jdlGenerationSettingEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlGenerationSetting_ServiceType()
  {
    return (EAttribute)jdlGenerationSettingEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlGenerationSetting_MicroserviceGenerationSetting()
  {
    return (EAttribute)jdlGenerationSettingEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlGenerationSetting_Appname()
  {
    return (EAttribute)jdlGenerationSettingEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlGenerationSetting_SearchGenerationSetting()
  {
    return (EAttribute)jdlGenerationSettingEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlGenerationSetting_Service()
  {
    return (EAttribute)jdlGenerationSettingEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlGenerationSetting_DtoGenerationSetting()
  {
    return (EAttribute)jdlGenerationSettingEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlGenerationSetting_DtoType()
  {
    return (EAttribute)jdlGenerationSettingEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlGenerationSetting_PaginateGenerationSetting()
  {
    return (EAttribute)jdlGenerationSettingEClass.getEStructuralFeatures().get(11);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlGenerationSetting_PaginateType()
  {
    return (EReference)jdlGenerationSettingEClass.getEStructuralFeatures().get(12);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlGenerationSetting_AngularSuffixGenerationSetting()
  {
    return (EAttribute)jdlGenerationSettingEClass.getEStructuralFeatures().get(13);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlGenerationSetting_Id()
  {
    return (EAttribute)jdlGenerationSettingEClass.getEStructuralFeatures().get(14);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlGenerationSettingType()
  {
    return jdlGenerationSettingTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlEntityInclusion()
  {
    return jdlEntityInclusionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlEntityInclusion_Predicate()
  {
    return (EReference)jdlEntityInclusionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlEntityInclusion_Entities()
  {
    return (EReference)jdlEntityInclusionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlEntityExclusion()
  {
    return jdlEntityExclusionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJdlEntityExclusion_Entities()
  {
    return (EReference)jdlEntityExclusionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlWildcardPredicate()
  {
    return jdlWildcardPredicateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlWildcardPredicate_Wildcard()
  {
    return (EAttribute)jdlWildcardPredicateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlWildcardPredicate_All()
  {
    return (EAttribute)jdlWildcardPredicateEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJdlPaginateType()
  {
    return jdlPaginateTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlPaginateType_Pagination()
  {
    return (EAttribute)jdlPaginateTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJdlPaginateType_InfiniteScroll()
  {
    return (EAttribute)jdlPaginateTypeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getJdlNumericFieldType()
  {
    return jdlNumericFieldTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getJdlBlobFieldType()
  {
    return jdlBlobFieldTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getJdlCardinality()
  {
    return jdlCardinalityEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getJdlServiceType()
  {
    return jdlServiceTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getJdlDtoType()
  {
    return jdlDtoTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public JdlFactory getJdlFactory()
  {
    return (JdlFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    jdlDomainModelEClass = createEClass(JDL_DOMAIN_MODEL);
    createEReference(jdlDomainModelEClass, JDL_DOMAIN_MODEL__FEATURES);

    jdlFeatureEClass = createEClass(JDL_FEATURE);

    jdlEntityEClass = createEClass(JDL_ENTITY);
    createEAttribute(jdlEntityEClass, JDL_ENTITY__NAME);
    createEReference(jdlEntityEClass, JDL_ENTITY__FIELDS);

    jdlEntityFieldEClass = createEClass(JDL_ENTITY_FIELD);
    createEAttribute(jdlEntityFieldEClass, JDL_ENTITY_FIELD__NAME);
    createEReference(jdlEntityFieldEClass, JDL_ENTITY_FIELD__TYPE);
    createEReference(jdlEntityFieldEClass, JDL_ENTITY_FIELD__ENUM_TYPE);
    createEAttribute(jdlEntityFieldEClass, JDL_ENTITY_FIELD__STRING_TYPE);
    createEAttribute(jdlEntityFieldEClass, JDL_ENTITY_FIELD__NUMERIC_FIELD_TYPE);
    createEAttribute(jdlEntityFieldEClass, JDL_ENTITY_FIELD__BOOLEAN_TYPE);
    createEAttribute(jdlEntityFieldEClass, JDL_ENTITY_FIELD__LOCAL_DATE_TYPE);
    createEAttribute(jdlEntityFieldEClass, JDL_ENTITY_FIELD__ZONED_DATE_TIME_TYPE);

    jdlFieldTypeEClass = createEClass(JDL_FIELD_TYPE);
    createEAttribute(jdlFieldTypeEClass, JDL_FIELD_TYPE__BLOB_FIELD_TYPE);
    createEReference(jdlFieldTypeEClass, JDL_FIELD_TYPE__VALIDATORS);

    jdlStringValidatorsEClass = createEClass(JDL_STRING_VALIDATORS);
    createEAttribute(jdlStringValidatorsEClass, JDL_STRING_VALIDATORS__REQUIRED);
    createEReference(jdlStringValidatorsEClass, JDL_STRING_VALIDATORS__MIN_LENGTH);
    createEReference(jdlStringValidatorsEClass, JDL_STRING_VALIDATORS__MAXLENGTH);
    createEReference(jdlStringValidatorsEClass, JDL_STRING_VALIDATORS__PATTERN);

    jdlNumericValidatorsEClass = createEClass(JDL_NUMERIC_VALIDATORS);
    createEReference(jdlNumericValidatorsEClass, JDL_NUMERIC_VALIDATORS__REQUIRED);
    createEReference(jdlNumericValidatorsEClass, JDL_NUMERIC_VALIDATORS__MINLENGTH);
    createEReference(jdlNumericValidatorsEClass, JDL_NUMERIC_VALIDATORS__MAXLENGTH);

    jdlBlobValidatorsEClass = createEClass(JDL_BLOB_VALIDATORS);
    createEReference(jdlBlobValidatorsEClass, JDL_BLOB_VALIDATORS__REQUIRED);
    createEReference(jdlBlobValidatorsEClass, JDL_BLOB_VALIDATORS__MINBYTES);
    createEReference(jdlBlobValidatorsEClass, JDL_BLOB_VALIDATORS__MAXBYTES);

    jdlRequiredValidatorEClass = createEClass(JDL_REQUIRED_VALIDATOR);
    createEAttribute(jdlRequiredValidatorEClass, JDL_REQUIRED_VALIDATOR__REQUIRED);

    jdlMinLengthValidatorEClass = createEClass(JDL_MIN_LENGTH_VALIDATOR);
    createEAttribute(jdlMinLengthValidatorEClass, JDL_MIN_LENGTH_VALIDATOR__VALUE);

    jdlMaxLengthValidatorEClass = createEClass(JDL_MAX_LENGTH_VALIDATOR);
    createEAttribute(jdlMaxLengthValidatorEClass, JDL_MAX_LENGTH_VALIDATOR__VALUE);

    jdlPatternValidatorEClass = createEClass(JDL_PATTERN_VALIDATOR);
    createEAttribute(jdlPatternValidatorEClass, JDL_PATTERN_VALIDATOR__VALUE);

    jdlMinValidatorEClass = createEClass(JDL_MIN_VALIDATOR);
    createEAttribute(jdlMinValidatorEClass, JDL_MIN_VALIDATOR__VALUE);

    jdlMaxValidatorEClass = createEClass(JDL_MAX_VALIDATOR);
    createEAttribute(jdlMaxValidatorEClass, JDL_MAX_VALIDATOR__VALUE);

    jdlMinBytesValidatorEClass = createEClass(JDL_MIN_BYTES_VALIDATOR);
    createEAttribute(jdlMinBytesValidatorEClass, JDL_MIN_BYTES_VALIDATOR__VALUE);

    jdlMaxBytesValidatorEClass = createEClass(JDL_MAX_BYTES_VALIDATOR);
    createEAttribute(jdlMaxBytesValidatorEClass, JDL_MAX_BYTES_VALIDATOR__VALUE);

    jdlRelationshipsEClass = createEClass(JDL_RELATIONSHIPS);
    createEAttribute(jdlRelationshipsEClass, JDL_RELATIONSHIPS__CARDINALITY);
    createEReference(jdlRelationshipsEClass, JDL_RELATIONSHIPS__RELATIONSHIPS);

    jdlRelationshipEClass = createEClass(JDL_RELATIONSHIP);
    createEReference(jdlRelationshipEClass, JDL_RELATIONSHIP__FROM_ENTITY);
    createEReference(jdlRelationshipEClass, JDL_RELATIONSHIP__FROM_NAME);
    createEReference(jdlRelationshipEClass, JDL_RELATIONSHIP__TO_ENTITY);
    createEReference(jdlRelationshipEClass, JDL_RELATIONSHIP__TO_NAME);

    jdlRelationshipNameEClass = createEClass(JDL_RELATIONSHIP_NAME);
    createEAttribute(jdlRelationshipNameEClass, JDL_RELATIONSHIP_NAME__NAME);
    createEAttribute(jdlRelationshipNameEClass, JDL_RELATIONSHIP_NAME__ROLE);

    jdlEnumTypeEClass = createEClass(JDL_ENUM_TYPE);
    createEAttribute(jdlEnumTypeEClass, JDL_ENUM_TYPE__NAME);
    createEAttribute(jdlEnumTypeEClass, JDL_ENUM_TYPE__VALUES);

    jdlGenerationSettingEClass = createEClass(JDL_GENERATION_SETTING);
    createEReference(jdlGenerationSettingEClass, JDL_GENERATION_SETTING__SETTING);
    createEReference(jdlGenerationSettingEClass, JDL_GENERATION_SETTING__EXCLUDES);
    createEAttribute(jdlGenerationSettingEClass, JDL_GENERATION_SETTING__SERVICE_GENERATION_SETTING);
    createEReference(jdlGenerationSettingEClass, JDL_GENERATION_SETTING__INCLUDES);
    createEAttribute(jdlGenerationSettingEClass, JDL_GENERATION_SETTING__SERVICE_TYPE);
    createEAttribute(jdlGenerationSettingEClass, JDL_GENERATION_SETTING__MICROSERVICE_GENERATION_SETTING);
    createEAttribute(jdlGenerationSettingEClass, JDL_GENERATION_SETTING__APPNAME);
    createEAttribute(jdlGenerationSettingEClass, JDL_GENERATION_SETTING__SEARCH_GENERATION_SETTING);
    createEAttribute(jdlGenerationSettingEClass, JDL_GENERATION_SETTING__SERVICE);
    createEAttribute(jdlGenerationSettingEClass, JDL_GENERATION_SETTING__DTO_GENERATION_SETTING);
    createEAttribute(jdlGenerationSettingEClass, JDL_GENERATION_SETTING__DTO_TYPE);
    createEAttribute(jdlGenerationSettingEClass, JDL_GENERATION_SETTING__PAGINATE_GENERATION_SETTING);
    createEReference(jdlGenerationSettingEClass, JDL_GENERATION_SETTING__PAGINATE_TYPE);
    createEAttribute(jdlGenerationSettingEClass, JDL_GENERATION_SETTING__ANGULAR_SUFFIX_GENERATION_SETTING);
    createEAttribute(jdlGenerationSettingEClass, JDL_GENERATION_SETTING__ID);

    jdlGenerationSettingTypeEClass = createEClass(JDL_GENERATION_SETTING_TYPE);

    jdlEntityInclusionEClass = createEClass(JDL_ENTITY_INCLUSION);
    createEReference(jdlEntityInclusionEClass, JDL_ENTITY_INCLUSION__PREDICATE);
    createEReference(jdlEntityInclusionEClass, JDL_ENTITY_INCLUSION__ENTITIES);

    jdlEntityExclusionEClass = createEClass(JDL_ENTITY_EXCLUSION);
    createEReference(jdlEntityExclusionEClass, JDL_ENTITY_EXCLUSION__ENTITIES);

    jdlWildcardPredicateEClass = createEClass(JDL_WILDCARD_PREDICATE);
    createEAttribute(jdlWildcardPredicateEClass, JDL_WILDCARD_PREDICATE__WILDCARD);
    createEAttribute(jdlWildcardPredicateEClass, JDL_WILDCARD_PREDICATE__ALL);

    jdlPaginateTypeEClass = createEClass(JDL_PAGINATE_TYPE);
    createEAttribute(jdlPaginateTypeEClass, JDL_PAGINATE_TYPE__PAGINATION);
    createEAttribute(jdlPaginateTypeEClass, JDL_PAGINATE_TYPE__INFINITE_SCROLL);

    // Create enums
    jdlNumericFieldTypeEEnum = createEEnum(JDL_NUMERIC_FIELD_TYPE);
    jdlBlobFieldTypeEEnum = createEEnum(JDL_BLOB_FIELD_TYPE);
    jdlCardinalityEEnum = createEEnum(JDL_CARDINALITY);
    jdlServiceTypeEEnum = createEEnum(JDL_SERVICE_TYPE);
    jdlDtoTypeEEnum = createEEnum(JDL_DTO_TYPE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    jdlEntityEClass.getESuperTypes().add(this.getJdlFeature());
    jdlEntityFieldEClass.getESuperTypes().add(this.getJdlFieldType());
    jdlRelationshipsEClass.getESuperTypes().add(this.getJdlFeature());
    jdlEnumTypeEClass.getESuperTypes().add(this.getJdlFeature());
    jdlGenerationSettingEClass.getESuperTypes().add(this.getJdlFeature());
    jdlGenerationSettingEClass.getESuperTypes().add(this.getJdlGenerationSettingType());

    // Initialize classes and features; add operations and parameters
    initEClass(jdlDomainModelEClass, JdlDomainModel.class, "JdlDomainModel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getJdlDomainModel_Features(), this.getJdlFeature(), null, "features", null, 0, -1, JdlDomainModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlFeatureEClass, JdlFeature.class, "JdlFeature", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(jdlEntityEClass, JdlEntity.class, "JdlEntity", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJdlEntity_Name(), ecorePackage.getEString(), "name", null, 0, 1, JdlEntity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlEntity_Fields(), this.getJdlEntityField(), null, "fields", null, 0, -1, JdlEntity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlEntityFieldEClass, JdlEntityField.class, "JdlEntityField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJdlEntityField_Name(), ecorePackage.getEString(), "name", null, 0, 1, JdlEntityField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlEntityField_Type(), this.getJdlFieldType(), null, "type", null, 0, 1, JdlEntityField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlEntityField_EnumType(), this.getJdlEnumType(), null, "enumType", null, 0, 1, JdlEntityField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlEntityField_StringType(), ecorePackage.getEBoolean(), "stringType", null, 0, 1, JdlEntityField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlEntityField_NumericFieldType(), this.getJdlNumericFieldType(), "numericFieldType", null, 0, 1, JdlEntityField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlEntityField_BooleanType(), ecorePackage.getEBoolean(), "booleanType", null, 0, 1, JdlEntityField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlEntityField_LocalDateType(), ecorePackage.getEBoolean(), "localDateType", null, 0, 1, JdlEntityField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlEntityField_ZonedDateTimeType(), ecorePackage.getEBoolean(), "zonedDateTimeType", null, 0, 1, JdlEntityField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlFieldTypeEClass, JdlFieldType.class, "JdlFieldType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJdlFieldType_BlobFieldType(), this.getJdlBlobFieldType(), "blobFieldType", null, 0, 1, JdlFieldType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlFieldType_Validators(), ecorePackage.getEObject(), null, "validators", null, 0, 1, JdlFieldType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlStringValidatorsEClass, JdlStringValidators.class, "JdlStringValidators", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJdlStringValidators_Required(), ecorePackage.getEBoolean(), "required", null, 0, 1, JdlStringValidators.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlStringValidators_MinLength(), this.getJdlMinLengthValidator(), null, "minLength", null, 0, 1, JdlStringValidators.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlStringValidators_Maxlength(), this.getJdlMaxLengthValidator(), null, "maxlength", null, 0, 1, JdlStringValidators.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlStringValidators_Pattern(), this.getJdlPatternValidator(), null, "pattern", null, 0, 1, JdlStringValidators.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlNumericValidatorsEClass, JdlNumericValidators.class, "JdlNumericValidators", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getJdlNumericValidators_Required(), this.getJdlRequiredValidator(), null, "required", null, 0, 1, JdlNumericValidators.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlNumericValidators_Minlength(), this.getJdlMinValidator(), null, "minlength", null, 0, 1, JdlNumericValidators.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlNumericValidators_Maxlength(), this.getJdlMaxValidator(), null, "maxlength", null, 0, 1, JdlNumericValidators.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlBlobValidatorsEClass, JdlBlobValidators.class, "JdlBlobValidators", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getJdlBlobValidators_Required(), this.getJdlRequiredValidator(), null, "required", null, 0, 1, JdlBlobValidators.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlBlobValidators_Minbytes(), this.getJdlMinBytesValidator(), null, "minbytes", null, 0, 1, JdlBlobValidators.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlBlobValidators_Maxbytes(), this.getJdlMaxBytesValidator(), null, "maxbytes", null, 0, 1, JdlBlobValidators.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlRequiredValidatorEClass, JdlRequiredValidator.class, "JdlRequiredValidator", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJdlRequiredValidator_Required(), ecorePackage.getEBoolean(), "required", null, 0, 1, JdlRequiredValidator.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlMinLengthValidatorEClass, JdlMinLengthValidator.class, "JdlMinLengthValidator", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJdlMinLengthValidator_Value(), ecorePackage.getEInt(), "value", null, 0, 1, JdlMinLengthValidator.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlMaxLengthValidatorEClass, JdlMaxLengthValidator.class, "JdlMaxLengthValidator", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJdlMaxLengthValidator_Value(), ecorePackage.getEInt(), "value", null, 0, 1, JdlMaxLengthValidator.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlPatternValidatorEClass, JdlPatternValidator.class, "JdlPatternValidator", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJdlPatternValidator_Value(), ecorePackage.getEString(), "value", null, 0, 1, JdlPatternValidator.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlMinValidatorEClass, JdlMinValidator.class, "JdlMinValidator", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJdlMinValidator_Value(), ecorePackage.getEInt(), "value", null, 0, 1, JdlMinValidator.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlMaxValidatorEClass, JdlMaxValidator.class, "JdlMaxValidator", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJdlMaxValidator_Value(), ecorePackage.getEInt(), "value", null, 0, 1, JdlMaxValidator.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlMinBytesValidatorEClass, JdlMinBytesValidator.class, "JdlMinBytesValidator", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJdlMinBytesValidator_Value(), ecorePackage.getEInt(), "value", null, 0, 1, JdlMinBytesValidator.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlMaxBytesValidatorEClass, JdlMaxBytesValidator.class, "JdlMaxBytesValidator", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJdlMaxBytesValidator_Value(), ecorePackage.getEInt(), "value", null, 0, 1, JdlMaxBytesValidator.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlRelationshipsEClass, JdlRelationships.class, "JdlRelationships", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJdlRelationships_Cardinality(), this.getJdlCardinality(), "cardinality", null, 0, 1, JdlRelationships.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlRelationships_Relationships(), this.getJdlRelationship(), null, "relationships", null, 0, -1, JdlRelationships.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlRelationshipEClass, JdlRelationship.class, "JdlRelationship", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getJdlRelationship_FromEntity(), this.getJdlEntity(), null, "fromEntity", null, 0, 1, JdlRelationship.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlRelationship_FromName(), this.getJdlRelationshipName(), null, "fromName", null, 0, 1, JdlRelationship.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlRelationship_ToEntity(), this.getJdlEntity(), null, "toEntity", null, 0, 1, JdlRelationship.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlRelationship_ToName(), this.getJdlRelationshipName(), null, "toName", null, 0, 1, JdlRelationship.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlRelationshipNameEClass, JdlRelationshipName.class, "JdlRelationshipName", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJdlRelationshipName_Name(), ecorePackage.getEString(), "name", null, 0, 1, JdlRelationshipName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlRelationshipName_Role(), ecorePackage.getEString(), "role", null, 0, 1, JdlRelationshipName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlEnumTypeEClass, JdlEnumType.class, "JdlEnumType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJdlEnumType_Name(), ecorePackage.getEString(), "name", null, 0, 1, JdlEnumType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlEnumType_Values(), ecorePackage.getEString(), "values", null, 0, -1, JdlEnumType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlGenerationSettingEClass, JdlGenerationSetting.class, "JdlGenerationSetting", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getJdlGenerationSetting_Setting(), this.getJdlGenerationSettingType(), null, "setting", null, 0, 1, JdlGenerationSetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlGenerationSetting_Excludes(), this.getJdlEntityExclusion(), null, "excludes", null, 0, 1, JdlGenerationSetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlGenerationSetting_ServiceGenerationSetting(), ecorePackage.getEBoolean(), "serviceGenerationSetting", null, 0, 1, JdlGenerationSetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlGenerationSetting_Includes(), this.getJdlEntityInclusion(), null, "includes", null, 0, 1, JdlGenerationSetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlGenerationSetting_ServiceType(), this.getJdlServiceType(), "serviceType", null, 0, 1, JdlGenerationSetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlGenerationSetting_MicroserviceGenerationSetting(), ecorePackage.getEBoolean(), "microserviceGenerationSetting", null, 0, 1, JdlGenerationSetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlGenerationSetting_Appname(), ecorePackage.getEString(), "appname", null, 0, 1, JdlGenerationSetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlGenerationSetting_SearchGenerationSetting(), ecorePackage.getEBoolean(), "searchGenerationSetting", null, 0, 1, JdlGenerationSetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlGenerationSetting_Service(), ecorePackage.getEString(), "service", null, 0, 1, JdlGenerationSetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlGenerationSetting_DtoGenerationSetting(), ecorePackage.getEBoolean(), "dtoGenerationSetting", null, 0, 1, JdlGenerationSetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlGenerationSetting_DtoType(), this.getJdlDtoType(), "dtoType", null, 0, 1, JdlGenerationSetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlGenerationSetting_PaginateGenerationSetting(), ecorePackage.getEBoolean(), "paginateGenerationSetting", null, 0, 1, JdlGenerationSetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlGenerationSetting_PaginateType(), this.getJdlPaginateType(), null, "paginateType", null, 0, 1, JdlGenerationSetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlGenerationSetting_AngularSuffixGenerationSetting(), ecorePackage.getEBoolean(), "angularSuffixGenerationSetting", null, 0, 1, JdlGenerationSetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlGenerationSetting_Id(), ecorePackage.getEString(), "id", null, 0, 1, JdlGenerationSetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlGenerationSettingTypeEClass, JdlGenerationSettingType.class, "JdlGenerationSettingType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(jdlEntityInclusionEClass, JdlEntityInclusion.class, "JdlEntityInclusion", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getJdlEntityInclusion_Predicate(), this.getJdlWildcardPredicate(), null, "predicate", null, 0, 1, JdlEntityInclusion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJdlEntityInclusion_Entities(), this.getJdlEntity(), null, "entities", null, 0, -1, JdlEntityInclusion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlEntityExclusionEClass, JdlEntityExclusion.class, "JdlEntityExclusion", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getJdlEntityExclusion_Entities(), this.getJdlEntity(), null, "entities", null, 0, -1, JdlEntityExclusion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlWildcardPredicateEClass, JdlWildcardPredicate.class, "JdlWildcardPredicate", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJdlWildcardPredicate_Wildcard(), ecorePackage.getEBoolean(), "wildcard", null, 0, 1, JdlWildcardPredicate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlWildcardPredicate_All(), ecorePackage.getEBoolean(), "all", null, 0, 1, JdlWildcardPredicate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jdlPaginateTypeEClass, JdlPaginateType.class, "JdlPaginateType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJdlPaginateType_Pagination(), ecorePackage.getEBoolean(), "pagination", null, 0, 1, JdlPaginateType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJdlPaginateType_InfiniteScroll(), ecorePackage.getEBoolean(), "infiniteScroll", null, 0, 1, JdlPaginateType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(jdlNumericFieldTypeEEnum, JdlNumericFieldType.class, "JdlNumericFieldType");
    addEEnumLiteral(jdlNumericFieldTypeEEnum, JdlNumericFieldType.INTEGER);
    addEEnumLiteral(jdlNumericFieldTypeEEnum, JdlNumericFieldType.LONG);
    addEEnumLiteral(jdlNumericFieldTypeEEnum, JdlNumericFieldType.BIG_DECIMAL);
    addEEnumLiteral(jdlNumericFieldTypeEEnum, JdlNumericFieldType.FLOAT);
    addEEnumLiteral(jdlNumericFieldTypeEEnum, JdlNumericFieldType.DOUBLE);

    initEEnum(jdlBlobFieldTypeEEnum, JdlBlobFieldType.class, "JdlBlobFieldType");
    addEEnumLiteral(jdlBlobFieldTypeEEnum, JdlBlobFieldType.BLOB);
    addEEnumLiteral(jdlBlobFieldTypeEEnum, JdlBlobFieldType.ANY_BLOB);
    addEEnumLiteral(jdlBlobFieldTypeEEnum, JdlBlobFieldType.IMAGE_BLOB);

    initEEnum(jdlCardinalityEEnum, JdlCardinality.class, "JdlCardinality");
    addEEnumLiteral(jdlCardinalityEEnum, JdlCardinality.ONE_TO_MANY);
    addEEnumLiteral(jdlCardinalityEEnum, JdlCardinality.MANY_TO_ONE);
    addEEnumLiteral(jdlCardinalityEEnum, JdlCardinality.ONE_TO_ONE);
    addEEnumLiteral(jdlCardinalityEEnum, JdlCardinality.MANY_TO_MANY);

    initEEnum(jdlServiceTypeEEnum, JdlServiceType.class, "JdlServiceType");
    addEEnumLiteral(jdlServiceTypeEEnum, JdlServiceType.SERVICE_CLASS);
    addEEnumLiteral(jdlServiceTypeEEnum, JdlServiceType.SERVICE_IMPL);

    initEEnum(jdlDtoTypeEEnum, JdlDtoType.class, "JdlDtoType");
    addEEnumLiteral(jdlDtoTypeEEnum, JdlDtoType.MAPSTRUCT);

    // Create resource
    createResource(eNS_URI);
  }

} //JdlPackageImpl
