/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.dsl;

import io.github.jhipster.jdl.dsl.AbstractJDLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class JDLRuntimeModule extends AbstractJDLRuntimeModule {
}
