/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.dsl.web;

import com.google.inject.Provider;
import io.github.jhipster.jdl.dsl.web.AbstractJDLWebModule;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class JDLWebModule extends AbstractJDLWebModule {
  public JDLWebModule(final Provider<ExecutorService> executorServiceProvider) {
    super(executorServiceProvider);
  }
}
