/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.jdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Exclusion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.jhipster.jdl.jdl.JdlEntityExclusion#getEntities <em>Entities</em>}</li>
 * </ul>
 *
 * @see io.github.jhipster.jdl.jdl.JdlPackage#getJdlEntityExclusion()
 * @model
 * @generated
 */
public interface JdlEntityExclusion extends EObject
{
  /**
   * Returns the value of the '<em><b>Entities</b></em>' reference list.
   * The list contents are of type {@link io.github.jhipster.jdl.jdl.JdlEntity}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entities</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' reference list.
   * @see io.github.jhipster.jdl.jdl.JdlPackage#getJdlEntityExclusion_Entities()
   * @model
   * @generated
   */
  EList<JdlEntity> getEntities();

} // JdlEntityExclusion
