/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.jdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.jhipster.jdl.jdl.JdlFieldType#getBlobFieldType <em>Blob Field Type</em>}</li>
 *   <li>{@link io.github.jhipster.jdl.jdl.JdlFieldType#getValidators <em>Validators</em>}</li>
 * </ul>
 *
 * @see io.github.jhipster.jdl.jdl.JdlPackage#getJdlFieldType()
 * @model
 * @generated
 */
public interface JdlFieldType extends EObject
{
  /**
   * Returns the value of the '<em><b>Blob Field Type</b></em>' attribute.
   * The literals are from the enumeration {@link io.github.jhipster.jdl.jdl.JdlBlobFieldType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Blob Field Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Blob Field Type</em>' attribute.
   * @see io.github.jhipster.jdl.jdl.JdlBlobFieldType
   * @see #setBlobFieldType(JdlBlobFieldType)
   * @see io.github.jhipster.jdl.jdl.JdlPackage#getJdlFieldType_BlobFieldType()
   * @model
   * @generated
   */
  JdlBlobFieldType getBlobFieldType();

  /**
   * Sets the value of the '{@link io.github.jhipster.jdl.jdl.JdlFieldType#getBlobFieldType <em>Blob Field Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Blob Field Type</em>' attribute.
   * @see io.github.jhipster.jdl.jdl.JdlBlobFieldType
   * @see #getBlobFieldType()
   * @generated
   */
  void setBlobFieldType(JdlBlobFieldType value);

  /**
   * Returns the value of the '<em><b>Validators</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Validators</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Validators</em>' containment reference.
   * @see #setValidators(EObject)
   * @see io.github.jhipster.jdl.jdl.JdlPackage#getJdlFieldType_Validators()
   * @model containment="true"
   * @generated
   */
  EObject getValidators();

  /**
   * Sets the value of the '{@link io.github.jhipster.jdl.jdl.JdlFieldType#getValidators <em>Validators</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Validators</em>' containment reference.
   * @see #getValidators()
   * @generated
   */
  void setValidators(EObject value);

} // JdlFieldType
