/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.jdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Generation Setting Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.github.jhipster.jdl.jdl.JdlPackage#getJdlGenerationSettingType()
 * @model
 * @generated
 */
public interface JdlGenerationSettingType extends EObject
{
} // JdlGenerationSettingType
