/**
 * generated by Xtext 2.10.0
 */
package io.github.jhipster.jdl.jdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Max Bytes Validator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.jhipster.jdl.jdl.JdlMaxBytesValidator#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see io.github.jhipster.jdl.jdl.JdlPackage#getJdlMaxBytesValidator()
 * @model
 * @generated
 */
public interface JdlMaxBytesValidator extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see io.github.jhipster.jdl.jdl.JdlPackage#getJdlMaxBytesValidator_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link io.github.jhipster.jdl.jdl.JdlMaxBytesValidator#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

} // JdlMaxBytesValidator
